version: "3.8"

services:
  app:
    build: .
    command: ruby app.rb -o 0.0.0.0
    ports:
      - "4567:4567"
    volumes:
      - ".:/app"
    depends_on:
      - db
    env_file:
      - .env.development
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}

  db:
    image: postgres:15
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/app/db

volumes:
  pgdata:
