version: "3.8"

services:
  app:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - ".:/app"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/torisetsu_db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: torisetsu_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/app/db

volumes:
  pgdata:
